PUT http://localhost:3003/api/blogs 
Content-Type: application/json     
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvbWkiLCJpZCI6IjY0MTFjNmU2OTgwOTNmNDFjODViYWQ3MCIsImlhdCI6MTY4MTA0NDU3NiwiZXhwIjoxNjgxMDQ4MTc2fQ.oa887dIyC7bKtRTRwCG0kgKcubd3nCY8IMy4TooRHJY

{
   "title": "Road to Fullstack", 
"author": "Mariam Ismael", 
"likes": 8, 
"url": "www.mariamismael.com"  
}