POST http://localhost:3003/api/users 
Content-Type: application/json

{
"username": "Tomi", "name": "Mariam Ismael", "password": "mimi"
}

###
POST http://localhost:3003/api/users 
Content-Type: application/json

{
"username": "Ismael", "name": "Tomi Ismael", "password": "mariam"
} 